import { COMMON_ILLUSTRATIONS } from './common';
import { WESTERN_ILLUSTRATIONS } from './western';
import { JAPAN_ILLUSTRATIONS } from './japan';
import { AFRICA_ILLUSTRATIONS } from './africa';
import { HORROR_ILLUSTRATIONS } from './horror';
import { CYBERPUNK_ILLUSTRATIONS } from './cyberpunk';

export { COMMON_ILLUSTRATIONS, WESTERN_ILLUSTRATIONS, JAPAN_ILLUSTRATIONS, AFRICA_ILLUSTRATIONS, HORROR_ILLUSTRATIONS, CYBERPUNK_ILLUSTRATIONS };

export const CARD_ILLUSTRATIONS: { [key: string]: string } = {
  ...COMMON_ILLUSTRATIONS,
  ...WESTERN_ILLUSTRATIONS,
  ...JAPAN_ILLUSTRATIONS,
  ...AFRICA_ILLUSTRATIONS,
  ...HORROR_ILLUSTRATIONS,
  ...CYBERPUNK_ILLUSTRATIONS,
};